=== Priscilalopez142351/PriscilaLopez.github.io/textbooks.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="textbooks" type="xs:textbooksType"/>

    <xs:complexType name="textbooksType">
        <xs:sequence>
            <xs:element name="textbook" type="xs:textbookType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="textbookType">
        <xs:sequence>   
            <xs:element name="title" type="xs:string" />
            <xs:element name="author" type="authorType" minOccurs="1" maxOccurs="unbounded" />
            <xs:element name="publisher" type="xs:string" />
            <xs:element name="year" type="xs:positiveInteger" />
            <xs:element name="isbn" type="xs:string" />
            <xs:element name="edition" type="xs:string" />
            <xs:element name="covertype" type="xs:string"/>
            <xs:element name="website" type="xs:anyURI" minOccurs="0"/> 
        </xs:sequence>
    </xs:complexType>

<xs:complexType name="authorType">
        <xs:sequence>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="publisherType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="website" type="xs:anyURI"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== Priscilalopez142351/PriscilaLopez.github.io/textbooks.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type = "text/xsl" href = "textbooks.xsl"?>

<textbooks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="textbooks.xsd">
    <textbook>
        <title>Java How To Program (Early Objects) (10th Edition)</title>
        <firstName>Paul</firstName>
        <lastName>Deitel</lastName>
    </author>
    <author>
        <firstName>Harvey</firstName>
        <lastName>Deitel</lastName>
    </author>

        <publisher>Pearson</publisher>
        <year>2014</year>
        <isbn>0133807800</isbn>
        <edition>10th</edition>
        <covertype>Softcover</covertype>
        <website>https://www.pearson.com/en-us.html</website>
    </textbook>


    <textbook>
        <title>Internet and World Wide Web: How to Program with CD-ROM BK CD ROM</title>
        <author>
            <firstName>Paul</firstName>
        <lastName>Deitel</lastName>
    </author>
    <author>
        <firstName>Harvey</firstName>
        <lastName>Deitel</lastName>
    </author>
    <author>
            <firstName>T.</firstName>
            <lastName>Nieto</lastName>
    </author>
        <publisher>Prentice Hal</publisher>
        <year>2004</year>
        <isbn>0131450913</isbn>
        <edition>3rd</edition>
        <covertype>Paperback</covertype>
        <website>https://www.amazon.com/Internet-World-Wide-Web-Program/dp/0131450913</website>
    </textbook>
</textbooks>
